[cerebrium.deployment]
name = "4643"
python_version = "3.11"

[cerebrium.hardware]
cpu = 2
memory = 45.0
compute = "ADA_L40"
gpu_count = 1
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
replica_concurrency = 10
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100

[cerebrium.dependencies.pip]
fastapi = "latest"             # برای FastAPI
uvicorn = "latest"             # سرور
pydantic = "latest"            # برای مدل ورودی
diffusers = "latest"
torch = ">=2.3.0"
transformers = "latest"
accelerate = "latest"
safetensors = "latest"
sentencepiece = "latest"
pillow = "latest"
