[cerebrium.deployment]
python_version = "3.11"

[cerebrium.dependencies.pip]
fastapi = "latest"
uvicorn = "latest"
pydantic = "latest"
"diffusers[torch]" = "latest"
torch = ">=2.3.0"
pillow = "latest"
